import React from "react";
import AccountIcon from "../../../src/assets/icons/AccountIcon";
import AddPersonIcon from "../../../src/assets/icons/AddPersonIcon";
import ArrowIcon_Next from "../../../src/assets/icons/ArrowIcon_Next";
import BackIcon from "../../../src/assets/icons/BackIcon";
import Bell from "../../../src/assets/icons/Bell";
import BellIcon_Red from "../../../src/assets/icons/BellIcon_Red";
import Cake from "../../../src/assets/icons/Cake";
import Camera from "../../../src/assets/icons/Camera";
import CardIcon from "../../../src/assets/icons/CardIcon";
import Card_PurpleIcon from "../../../src/assets/icons/Card_PurpleIcon";
import Card_RedIcon from "../../../src/assets/icons/Card_RedIcon";
import Gender from "../../../src/assets/icons/Gender";
import GenderIcon from "../../../src/assets/icons/GenderIcon";
import HeadPhoneIcon from "../../../src/assets/icons/HeadphoneIcon";
import InfoIcon from "../../../src/assets/icons/InfoIcon";
import LogoutIcon from "../../../src/assets/icons/LogoutIcon";
import MapPinIcon from "../../../src/assets/icons/MapPinIcon";
import MedicalHistory from "../../../src/assets/icons/MedicalHistory";
import Message from "../../../src/assets/icons/Message";
import NextIcon from "../../../src/assets/icons/NextIcon";
import PenEditIcon from "../../../src/assets/icons/PenEditIcon";
import PhoneIcon from "../../../src/assets/icons/PhoneIcon";
import PriceTag from "../../../src/assets/icons/PriceTag";
import Rating from "../../../src/assets/icons/Rating";
import Report from "../../../src/assets/icons/Report";
import Search from "../../../src/assets/icons/Search";
import SquareCheckIcon from "../../../src/assets/icons/SquareCheckIcon";
import TabChatIconSvgComponent from "../../../src/assets/icons/TabChatIcon";
import TabHomeIcon from "../../../src/assets/icons/TabHomeIcon";
import TabProfileIcon from "../../../src/assets/icons/TabProfileIcon";
import TabScheduleIcon from "../../../src/assets/icons/TabScheduleIcon";
import UpdateClock from "../../../src/assets/icons/UpdateClock";
import User from "../../../src/assets/icons/User";
import WhatsAppLogo from "../../../src/assets/icons/WhatsAppLogo";

describe("Testing all icon's render", () => {
	test("are they rendered", () => {
		expect(AccountIcon(10)).toBeDefined();
		expect(AddPersonIcon(10)).toBeDefined();
		expect(ArrowIcon_Next(10)).toBeDefined();
		expect(BackIcon(10)).toBeDefined();
		expect(Bell(10)).toBeDefined();
		expect(BellIcon_Red(10)).toBeDefined();
		expect(Cake(10)).toBeDefined();
		expect(Camera(10)).toBeDefined();
		expect(Card_PurpleIcon(10)).toBeDefined();
		expect(Card_RedIcon(10)).toBeDefined();
		expect(CardIcon(10)).toBeDefined();
		expect(Gender(10)).toBeDefined();
		expect(GenderIcon(10)).toBeDefined();
		expect(HeadPhoneIcon(10)).toBeDefined();
		expect(InfoIcon(10)).toBeDefined();
		expect(LogoutIcon(10)).toBeDefined();
		expect(MapPinIcon(10)).toBeDefined();
		expect(MedicalHistory(10)).toBeDefined();
		expect(Message(10)).toBeDefined();
		expect(NextIcon(10)).toBeDefined();
		expect(PenEditIcon(10)).toBeDefined();
		expect(PhoneIcon(10)).toBeDefined();
		expect(PriceTag(10)).toBeDefined();
		expect(Rating(10)).toBeDefined();
		expect(Report(10)).toBeDefined();
		expect(Search(10)).toBeDefined();
		expect(SquareCheckIcon(10)).toBeDefined();
		expect(TabChatIconSvgComponent(10)).toBeDefined();
		expect(TabHomeIcon(10)).toBeDefined();
		expect(TabProfileIcon(10)).toBeDefined();
		expect(TabScheduleIcon(10)).toBeDefined();
		expect(UpdateClock(10)).toBeDefined();
		expect(User(10)).toBeDefined();
		expect(WhatsAppLogo(10)).toBeDefined();
	});
});
